package com.tedu.pojo;

import java.util.Date;

public class TbAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.user_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.address
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.added
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Date added;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.receiver
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.receiver_phone
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String receiverPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.rid
     *
     * @return the value of tb_address.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.rid
     *
     * @param rid the value for tb_address.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.user_id
     *
     * @return the value of tb_address.user_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.user_id
     *
     * @param userId the value for tb_address.user_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.address
     *
     * @return the value of tb_address.address
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.address
     *
     * @param address the value for tb_address.address
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.added
     *
     * @return the value of tb_address.added
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Date getAdded() {
        return added;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.added
     *
     * @param added the value for tb_address.added
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setAdded(Date added) {
        this.added = added;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.receiver
     *
     * @return the value of tb_address.receiver
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.receiver
     *
     * @param receiver the value for tb_address.receiver
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.receiver_phone
     *
     * @return the value of tb_address.receiver_phone
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.receiver_phone
     *
     * @param receiverPhone the value for tb_address.receiver_phone
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }
}