package com.tedu.pojo;

import java.util.Date;

public class TbBook {
    @Override
	public String toString() {
		return "TbBook [isbn=" + isbn + ", title=" + title + ", author=" + author + ", price=" + price + ", press="
				+ press + ", edition=" + edition + ", published=" + published + ", pages=" + pages + ", words=" + words
				+ ", packaging=" + packaging + ", format=" + format + ", form=" + form + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.isbn
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.title
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.author
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.price
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.press
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.edition
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer edition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.published
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Date published;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.pages
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer pages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.words
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer words;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.packaging
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String packaging;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.format
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.form
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String form;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.isbn
     *
     * @return the value of tb_book.isbn
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.isbn
     *
     * @param isbn the value for tb_book.isbn
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.title
     *
     * @return the value of tb_book.title
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.title
     *
     * @param title the value for tb_book.title
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.author
     *
     * @return the value of tb_book.author
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.author
     *
     * @param author the value for tb_book.author
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.price
     *
     * @return the value of tb_book.price
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.price
     *
     * @param price the value for tb_book.price
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.press
     *
     * @return the value of tb_book.press
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.press
     *
     * @param press the value for tb_book.press
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPress(String press) {
        this.press = press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.edition
     *
     * @return the value of tb_book.edition
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.edition
     *
     * @param edition the value for tb_book.edition
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.published
     *
     * @return the value of tb_book.published
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Date getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.published
     *
     * @param published the value for tb_book.published
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPublished(Date published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.pages
     *
     * @return the value of tb_book.pages
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.pages
     *
     * @param pages the value for tb_book.pages
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.words
     *
     * @return the value of tb_book.words
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.words
     *
     * @param words the value for tb_book.words
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setWords(Integer words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.packaging
     *
     * @return the value of tb_book.packaging
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getPackaging() {
        return packaging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.packaging
     *
     * @param packaging the value for tb_book.packaging
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPackaging(String packaging) {
        this.packaging = packaging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.format
     *
     * @return the value of tb_book.format
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.format
     *
     * @param format the value for tb_book.format
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.form
     *
     * @return the value of tb_book.form
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.form
     *
     * @param form the value for tb_book.form
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setForm(String form) {
        this.form = form;
    }
}