package com.tedu.pojo;

public class TbCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collect.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collect.user_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collect.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String product;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collect.rid
     *
     * @return the value of tb_collect.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collect.rid
     *
     * @param rid the value for tb_collect.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collect.user_id
     *
     * @return the value of tb_collect.user_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collect.user_id
     *
     * @param userId the value for tb_collect.user_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collect.product
     *
     * @return the value of tb_collect.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collect.product
     *
     * @param product the value for tb_collect.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setProduct(String product) {
        this.product = product;
    }
}