package com.tedu.pojo;

public class TbOrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String product;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.price
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.count
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.order_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.rid
     *
     * @return the value of tb_order_item.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.rid
     *
     * @param rid the value for tb_order_item.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.product
     *
     * @return the value of tb_order_item.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.product
     *
     * @param product the value for tb_order_item.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setProduct(String product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.price
     *
     * @return the value of tb_order_item.price
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.price
     *
     * @param price the value for tb_order_item.price
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.count
     *
     * @return the value of tb_order_item.count
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.count
     *
     * @param count the value for tb_order_item.count
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.order_id
     *
     * @return the value of tb_order_item.order_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.order_id
     *
     * @param orderId the value for tb_order_item.order_id
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
}