package com.tedu.pojo;

public class TbRecommended {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recommended.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recommended.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String product;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recommended.rid
     *
     * @return the value of tb_recommended.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recommended.rid
     *
     * @param rid the value for tb_recommended.rid
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recommended.product
     *
     * @return the value of tb_recommended.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recommended.product
     *
     * @param product the value for tb_recommended.product
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setProduct(String product) {
        this.product = product;
    }
}