package com.tedu.pojo;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uname
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.upwd
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.email
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.role
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uname
     *
     * @return the value of tb_user.uname
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uname
     *
     * @param uname the value for tb_user.uname
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.upwd
     *
     * @return the value of tb_user.upwd
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.upwd
     *
     * @param upwd the value for tb_user.upwd
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role
     *
     * @return the value of tb_user.role
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role
     *
     * @param role the value for tb_user.role
     *
     * @mbg.generated Fri Apr 08 11:05:42 HKT 2022
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}